version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: jetchat-postgres
    environment:
      POSTGRES_DB: modul_223_production
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - jetchat-network

  jetchat:
    image: masterbaiter/jetchat-ruby_on_rails:latest
    container_name: jetchat-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      RAILS_ENV: production
      SERVER_PORT: 5000
      # Database URL - should override database.yml completely
      DATABASE_URL: postgres://modul_223:postgres@postgres:5432/modul_223_production
      # Cache, Queue, and Cable database URLs for Rails multi-database setup
      CACHE_DATABASE_URL: postgres://modul_223:postgres@postgres:5432/modul_223_production_cache
      QUEUE_DATABASE_URL: postgres://modul_223:postgres@postgres:5432/modul_223_production_queue
      CABLE_DATABASE_URL: postgres://modul_223:postgres@postgres:5432/modul_223_production_cable
      # Database Configuration - matches database.yml production config
      MODUL_223_DATABASE_PASSWORD: postgres
      # Zitadel Configuration
      ZITADEL_ISSUER: https://jetchat-5jjotf.us1.zitadel.cloud
      ZITADEL_CLIENT_ID: "339386197019301969"
      # Rails Configuration
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY:-6e7e17f6ae38014e7e10f660e33fea06}
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_LOG_TO_STDOUT: "true"
      # Security
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:-your_secret_key_base}
    ports:
      - "5000:5000"
    volumes:
      - app_storage:/rails/storage
    networks:
      - jetchat-network
    restart: unless-stopped
    command: >
      sh -c "
        bin/rails db:create db:migrate &&
        bin/rails server -b 0.0.0.0 -p 5000
      "

volumes:
  postgres_data:
  app_storage:

networks:
  jetchat-network:
    driver: bridge